# Generated by Django 4.2.4 on 2023-08-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_sir_name_user_middle_name_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='middle_name_name',
            new_name='middle_name',
        ),
    ]
