# Generated by Django 4.2 on 2023-08-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_withdraw_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='transaction_cost',
            field=models.IntegerField(default=0),
        ),
    ]
