# Generated by Django 4.2 on 2023-08-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_account_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default='073247'),
        ),
    ]
